# docker-compose.yml
version: '3.8'

networks:
  compliamce_ai_net:
    driver: bridge

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    networks:
      - compliamce_ai_net
    volumes:
      - .:/app